# Generated by Django 5.0.6 on 2024-06-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subscription_duration'),
        ('brand', '0003_subscription_brand_sub_expire_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sub_expire',
        ),
    ]
