# Generated by Django 5.0.6 on 2024-06-06 15:35

import core.apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_subscription_remove_user_sub_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, validators=[core.apps.accounts.validators.phone_validator], verbose_name='Телефон'),
        ),
    ]
