# Generated by Django 5.0.6 on 2024-06-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(null=True, verbose_name='Идентификатор телеграм'),
        ),
    ]
