# Generated by Django 5.0.6 on 2024-06-17 18:38
import datetime

from django.db import migrations, models
from django.contrib.auth import get_user_model

def add_users(apps, schema_editor):
    User = get_user_model()

    staff_users = [
        User(
            email='staff@example.com',
            phone='+79998884422',
            date_joined=datetime.datetime.now(),
            is_active=True,
            is_staff=True,
        ),
        User(
            email='admin@example.com',
            phone='+79993332211',
            date_joined=datetime.datetime.now(),
            is_active=True,
            is_staff=True,
        )
    ]
    for user in staff_users:
        user.save()
        user.set_password('Pass!234')
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_telegram_id'),
    ]

    operations = [
        migrations.RunPython(add_users)
    ]
