# Generated by Django 5.0.6 on 2025-02-02 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0011_collaboration_match_match_like_at_match_match_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_as_blocked', to='brand.brand', verbose_name='Заблокирован')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_as_initiator', to='brand.brand', verbose_name='Добавил в ЧС')),
            ],
        ),
    ]
