# Generated by Django 5.1.6 on 2025-03-31 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blacklist', '0001_initial'),
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='blocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_as_blocked', to='brand.brand', verbose_name='Заблокирован'),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_as_initiator', to='brand.brand', verbose_name='Добавил в ЧС'),
        ),
    ]
