# Generated by Django 5.1.6 on 2025-03-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklist',
            options={'verbose_name': 'Blacklist', 'verbose_name_plural': 'Blacklist'},
        ),
    ]
