# Generated by Django 5.1.6 on 2025-05-16 17:08

import core.common.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('excerpt', models.CharField(max_length=255, verbose_name='Выдержка')),
                ('preview_video', models.FileField(upload_to='tutorials/preview_videos/', validators=[core.common.validators.is_valid_video], verbose_name='Превью видео')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('body', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='Контент')),
            ],
        ),
    ]
