# Generated by Django 5.1.6 on 2025-05-18 16:20

import core.apps.articles.models
import core.common.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tutorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('excerpt', models.CharField(max_length=255, verbose_name='Выдержка')),
                ('preview', models.ImageField(upload_to=core.apps.articles.models.article_preview_upload_path, validators=[core.common.validators.is_valid_image], verbose_name='Превью')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('body', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Community Article',
                'verbose_name_plural': 'Community Articles',
            },
        ),
    ]
