# Generated by Django 5.1.6 on 2025-05-18 17:49

import core.apps.articles.models
import core.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_community_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='preview_video',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='preview',
            field=models.FileField(default='', upload_to=core.apps.articles.models.article_preview_upload_path, validators=[core.common.validators.is_valid_video], verbose_name='Превью видео'),
            preserve_default=False,
        ),
    ]
