services:
  django:
    container_name: django
    build:
      context: ../
      dockerfile: Dockerfile
    env_file:
      - ../.env
    tty: true
    ports:
      - "8000:8000"
    networks:
      - dev-net
    volumes:
      - ../core:/app/core


  bot:
    container_name: bot
    build:
      context: ../
      dockerfile: Dockerfile
    command: ["-m", "telegram_bot.bot"]
    env_file:
      - ../example.env
    tty: true
    networks:
      - dev-net


networks:
  dev-net:
    name: dev-net
    driver: bridge
