services:
  celery_worker:
    container_name: celery_worker
    image: w2w_django
    pull_policy: never
    env_file:
      - ../example.env
    restart: on-failure
    networks:
      - dev-net
    volumes:
      - ../core:/app/core  # it doesn't see DATABASES setting without it
    entrypoint:
      - celery
      - -A
      - core.config
      - worker
      - -l
      - INFO

  celery_beat:
    container_name: celery_beat
    image: w2w_django
    pull_policy: never
    env_file:
      - ../example.env
    depends_on:
      - celery_worker
    restart: on-failure
    networks:
      - dev-net
    entrypoint:
      - celery
      - -A
      - core.config
      - beat
      - -l
      - INFO

  flower:
    container_name: flower
    image: w2w_django
    ports:
      - "5555:5555"
    pull_policy: never
    env_file:
      - ../example.env
    networks:
      - dev-net
    entrypoint:
      - celery
      - -A
      - core.config
      - flower


networks:
  dev-net:
    name: dev-net
    driver: bridge
