services:
  w2w_db:
    container_name: w2w_db
    hostname: ${DB_HOST}
    image: public.ecr.aws/docker/library/postgres:15
    environment:
      POSTGRES_DB_FILE: /run/secrets/db_name
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - "${DB_PORT}:5432"
    networks:
      - dev-net
    volumes:
      - w2w_db_data:/var/lib/postgresql/data/
    secrets:
      - db_name
      - db_user
      - db_password

  redis:
    container_name: redis
    hostname: ${REDIS_HOST}
    image: public.ecr.aws/docker/library/redis:7.2.4
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - dev-net

  rabbitmq:
    container_name: rabbitmq
    hostname: ${RABBITMQ_HOST}
    image: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
    networks:
      - dev-net
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}


volumes:
  w2w_db_data:
    name: w2w_db_data


networks:
  dev-net:
    name: dev-net
    driver: bridge


secrets:
  db_name:
    file: ../secrets/db/db_name.txt
  db_user:
    file: ../secrets/db/db_user.txt
  db_password:
    file: ../secrets/db/db_password.txt
