# Generated by Django 5.1.6 on 2025-03-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('R', 'Registration'), ('D', 'Deletion'), ('P', 'Payment')], max_length=1, verbose_name='Действие')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Выполнено')),
            ],
        ),
        migrations.CreateModel(
            name='MatchActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_match', models.BooleanField(verbose_name='Метч')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
        ),
    ]
