# Generated by Django 5.0.6 on 2024-09-03 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0014_match_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_match', models.BooleanField(verbose_name='Метч')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_as_initiator', to='brand.brand', verbose_name='Кто лайкнул')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_as_target', to='brand.brand', verbose_name='Кого лайкнули')),
            ],
        ),
    ]
