# Generated by Django 5.1.6 on 2025-03-31 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandactivity',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity', to='brand.brand', verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='matchactivity',
            name='collab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity', to='brand.collaboration', verbose_name='Коллаборация'),
        ),
        migrations.AddField(
            model_name='matchactivity',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_as_initiator', to='brand.brand', verbose_name='Кто лайкнул'),
        ),
        migrations.AddField(
            model_name='matchactivity',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_as_target', to='brand.brand', verbose_name='Кого лайкнули'),
        ),
    ]
