# Generated by Django 5.0.6 on 2024-10-28 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('brand', '0006_collaboration'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchactivity',
            name='collab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity', to='brand.collaboration', verbose_name='Коллаборация'),
        ),
    ]
