# Generated by Django 5.0.6 on 2024-09-05 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('brand', '0014_match_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchactivity',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_as_initiator', to='brand.brand', verbose_name='Кто лайкнул'),
        ),
        migrations.AlterField(
            model_name='matchactivity',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_as_target', to='brand.brand', verbose_name='Кого лайкнули'),
        ),
    ]
