# Generated by Django 5.1.6 on 2025-03-31 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchActivity',
        ),
    ]
