# Generated by Django 5.0.6 on 2024-09-11 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_brandactivity'),
        ('brand', '0018_collaboration'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchactivity',
            name='collab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity', to='brand.collaboration', verbose_name='Коллаборация'),
        ),
    ]
