# Generated by Django 5.1.6 on 2025-03-31 16:39

import core.apps.brand.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Мужчины')),
                ('women', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Женщины')),
            ],
            options={
                'verbose_name': 'Возраст',
                'verbose_name_plural': 'Возраст',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Категория')),
                ('is_other', models.BooleanField(default=False, verbose_name='Другое')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Формат')),
                ('is_other', models.BooleanField(default=False, verbose_name='Другое')),
            ],
            options={
                'verbose_name': 'Формат',
                'verbose_name_plural': 'Форматы',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% мужчин')),
                ('women', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% женщин')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Бизнес задача')),
                ('is_other', models.BooleanField(default=False, verbose_name='Другое')),
            ],
            options={
                'verbose_name': 'Бизнес задача',
                'verbose_name_plural': 'Бизнес задачи',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тег')),
                ('is_other', models.BooleanField(default=False, verbose_name='Другое')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_nickname', models.CharField(blank=True, max_length=64, verbose_name='Ник в телеграме')),
                ('name', models.CharField(max_length=256, verbose_name='Название бренда')),
                ('position', models.CharField(max_length=256, verbose_name='Должность')),
                ('inst_url', models.URLField(blank=True, verbose_name='Бренд в Instagram')),
                ('vk_url', models.URLField(blank=True, verbose_name='Бренд в ВК')),
                ('tg_url', models.URLField(blank=True, verbose_name='Бренд в Telegram')),
                ('wb_url', models.URLField(blank=True, verbose_name='Магазин в ВБ')),
                ('lamoda_url', models.URLField(blank=True, verbose_name='Магазин в Lamoda')),
                ('site_url', models.URLField(blank=True, verbose_name='Сайт бренда')),
                ('subs_count', models.PositiveIntegerField(verbose_name='Кол-во подписчиков')),
                ('avg_bill', models.PositiveIntegerField(verbose_name='Средний чек')),
                ('uniqueness', models.CharField(max_length=512, verbose_name='Уникальность бренда')),
                ('logo', models.ImageField(upload_to=core.apps.brand.models.UserDirectoryPath('logo'), verbose_name='Лого')),
                ('photo', models.ImageField(upload_to=core.apps.brand.models.UserDirectoryPath('photo'), verbose_name='Фото представителя')),
                ('mission_statement', models.CharField(blank=True, max_length=512, verbose_name='Миссия бренда')),
                ('offline_space', models.CharField(blank=True, max_length=512, verbose_name='Оффлайн пространство')),
                ('problem_solving', models.CharField(blank=True, max_length=512, verbose_name='Какую проблему решает')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='cities_light.city', verbose_name='Город')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('categories_of_interest', models.ManyToManyField(blank=True, related_name='brands_as_interest', to='brand.category', verbose_name='Интересующие категории')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='brand.category', verbose_name='Категория')),
                ('formats', models.ManyToManyField(blank=True, related_name='brands', to='brand.format', verbose_name='Форматы коллабораций')),
                ('goals', models.ManyToManyField(blank=True, related_name='brands', to='brand.goal', verbose_name='Бизнес задачи')),
                ('tags', models.ManyToManyField(related_name='brands', to='brand.tag', verbose_name='Ценности')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.URLField(verbose_name='Блог')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='brand.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
        migrations.CreateModel(
            name='BusinessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название или ссылка')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_groups', to='brand.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Сообщество предпринимателей',
                'verbose_name_plural': 'Сообщества предпринимателей',
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.apps.brand.models.gallery_path, verbose_name='Фото')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='brand.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Фото для галереи',
                'verbose_name_plural': 'Фото для галереи',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_match', models.BooleanField(default=False, verbose_name='Метч')),
                ('like_at', models.DateTimeField(auto_now_add=True, verbose_name='Время лайка')),
                ('match_at', models.DateTimeField(default=None, null=True, verbose_name='Время метча')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiator', to='brand.brand', verbose_name='Кто лайкнул')),
                ('room', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.room')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target', to='brand.brand', verbose_name='Кого лайкнули')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('success_assessment', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка по 10 бальной шкале')),
                ('success_reason', models.CharField(max_length=512, verbose_name='Причина успеха')),
                ('to_improve', models.CharField(max_length=512, verbose_name='Что улучшить')),
                ('subs_received', models.IntegerField(verbose_name='Получено подписчиков')),
                ('leads_received', models.IntegerField(verbose_name='Получено лидов/заявок')),
                ('sales_growth', models.CharField(max_length=128, verbose_name='Прирост продаж')),
                ('audience_reach', models.PositiveIntegerField(verbose_name='Охват аудитории')),
                ('bill_change', models.CharField(max_length=128, verbose_name='Изменение ср. чека')),
                ('new_offers', models.BooleanField(verbose_name='Новые предложения')),
                ('new_offers_comment', models.CharField(blank=True, max_length=512, verbose_name='Комментарий про предложения')),
                ('perception_change', models.BooleanField(verbose_name='Изменение восприятия бренда')),
                ('brand_compliance', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Соответствие брендов')),
                ('platform_help', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Помощь платформы')),
                ('difficulties', models.BooleanField(verbose_name='Трудности')),
                ('difficulties_comment', models.CharField(blank=True, max_length=512, verbose_name='Комментарий про трудности')),
                ('collab_with', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collab_participant', to='brand.brand', verbose_name='Коллаборация с')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collab_reporter', to='brand.brand', verbose_name='Кто поделился')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaborations', to='brand.match', verbose_name='Метч')),
            ],
            options={
                'verbose_name': 'Collaboration',
                'verbose_name_plural': 'Collaborations',
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('M', 'Для метча'), ('C', 'Для карточки бренда')], max_length=1, verbose_name='Формат изображения')),
                ('image', models.ImageField(upload_to=core.apps.brand.models.product_photo_path, verbose_name='Фото')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_photos', to='brand.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Фото продукта',
                'verbose_name_plural': 'Фото продукта',
            },
        ),
        migrations.CreateModel(
            name='TargetAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50000), django.core.validators.MaxValueValidator(1000000)], verbose_name='Доход')),
                ('age', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_audience', to='brand.age', verbose_name='Возраст')),
                ('gender', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_audience', to='brand.gender', verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Целевая аудитория',
                'verbose_name_plural': 'Целевая аудитория',
            },
        ),
        migrations.CreateModel(
            name='GEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_percentage', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент людей')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geos', to='cities_light.city', verbose_name='Город')),
                ('target_audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geos', to='brand.targetaudience', verbose_name='Целевая аудитория')),
            ],
            options={
                'verbose_name': 'ГЕО',
                'verbose_name_plural': 'ГЕО',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='target_audience',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='brand.targetaudience', verbose_name='Целевая аудитория'),
        ),
    ]
