# Generated by Django 5.0.6 on 2024-06-01 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subscription_duration'),
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='accounts.subscription', verbose_name='Тариф'),
            preserve_default=False,
        ),
    ]
