# Generated by Django 5.0.6 on 2024-10-19 12:13

from django.db import migrations


def add_tags(apps, schema_editor):
    Tag = apps.get_model('brand', 'Tag')

    tags = [
        Tag(name='Высокое качество'),
        Tag(name='Свобода'),
        Tag(name='Социальная значимость'),
        Tag(name='Минимализм'),
        Tag(name='Баланс'),
        Tag(name='Креатив'),
        Tag(name='Эстетика'),
        Tag(name='Творчество'),
        Tag(name='Доступность'),
        Tag(name='Скорость'),
        Tag(name='Природа'),
        Tag(name='Любовь'),
        Tag(name='Безопасность'),
        Tag(name='Самобытность'),
        Tag(name='Активность'),
        Tag(name='Семья'),
        Tag(name='Наследие'),
        Tag(name='Smart'),
        Tag(name='Комфорт'),
        Tag(name='Изысканность'),
        Tag(name='Забота о себе'),
        Tag(name='Сексуальность'),
        Tag(name='Эксклюзив'),
        Tag(name='Жизнерадостность'),
        Tag(name='Индивидуальный подход'),
        Tag(name='Культура'),
        Tag(name='Вдохновение'),
        Tag(name='Экологичность'),
        Tag(name='Инновационность'),
        Tag(name='Стиль'),
        Tag(name='Ручная работа'),
        Tag(name='Премиум'),
        Tag(name='Современность'),
        Tag(name='Расслабление'),
        Tag(name='Баланс'),
        Tag(name='Удовольствие'),
        Tag(name='Праздник'),
    ]

    Tag.objects.bulk_create(tags)


def delete_tags(apps, schema_editor):
    Tag = apps.get_model('brand', 'Tag')

    Tag.objects.filter(is_other=False, name__in=[
        'Высокое качество',
        'Свобода',
        'Социальная значимость',
        'Минимализм',
        'Баланс',
        'Креатив',
        'Эстетика',
        'Творчество',
        'Доступность',
        'Скорость',
        'Природа',
        'Любовь',
        'Безопасность',
        'Самобытность',
        'Активность',
        'Семья',
        'Наследие',
        'Smart',
        'Комфорт',
        'Изысканность',
        'Забота о себе',
        'Сексуальность',
        'Эксклюзив',
        'Жизнерадостность',
        'Индивидуальный подход',
        'Культура',
        'Вдохновение',
        'Экологичность',
        'Инновационность',
        'Стиль',
        'Ручная работа',
        'Премиум',
        'Современность',
        'Расслабление',
        'Баланс',
        'Удовольствие',
        'Праздник',
    ]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_tags, delete_tags)
    ]
