# Generated by Django 5.0.6 on 2024-06-01 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_brand_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тариф')),
                ('cost', models.PositiveIntegerField(verbose_name='Цена')),
                ('duration', models.DurationField(verbose_name='Продолжительность')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='sub_expire',
            field=models.DateField(null=True, verbose_name='Окончание подписки'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='brand.subscription', verbose_name='Тариф'),
        ),
    ]
