# Generated by Django 5.1.6 on 2025-03-31 16:44

from django.db import migrations


def add_categories(apps, schema_editor):
    Category = apps.get_model('brand', 'Category')

    categories = [
        Category(name='HoReCa'),
        Category(name='Kids'),
        Category(name='Home & design'),
        Category(name='Fashion'),
        Category(name='Health & beauty'),
        Category(name='Wellness & sport'),
        Category(name='Education & Art'),
        Category(name='Influencers'),
        Category(name='Charity'),
        Category(name='Services'),
    ]

    Category.objects.bulk_create(categories)


def delete_categories(apps, schema_editor):
    Category = apps.get_model('brand', 'Category')

    Category.objects.filter(is_other=False, name__in=[
        'HoReCa',
        'Kids',
        'Home & design',
        'Fashion',
        'Health & beauty',
        'Wellness & sport',
        'Education & Art',
        'Influencers',
        'Charity',
        'Services',
    ]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('brand', '0002_tags'),
    ]

    operations = [
        migrations.RunPython(add_categories, delete_categories)
    ]
