# Generated by Django 5.0.6 on 2024-06-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_subscription_brand_sub_expire_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='user_id',
            new_name='user',
        ),
    ]
