# Generated by Django 5.0.6 on 2024-06-12 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_rename_user_id_brand_user'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='payments.subscription', verbose_name='Тариф'),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
