# Generated by Django 5.0.6 on 2024-10-17 11:49

from django.db import migrations


def add_goals(apps, schema_editor):
    Goal = apps.get_model('brand', 'Goal')

    goals = [
        Goal(name='Продажи'),
        Goal(name='Охваты'),
        Goal(name='Подписчики'),
        Goal(name='Шеринг кастов'),
        Goal(name='Новый продукт'),
    ]

    Goal.objects.bulk_create(goals)


def delete_goals(apps, schema_editor):
    Goal = apps.get_model('brand', 'Goal')

    Goal.objects.filter(is_other=False, name__in=[
        'Продажи',
        'Охваты',
        'Подписчики',
        'Шеринг кастов',
        'Новый продукт',
    ]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('brand', '0004_formats'),
    ]

    operations = [
        migrations.RunPython(add_goals, delete_goals)
    ]
