# Generated by Django 5.0.6 on 2024-06-13 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0005_alter_brand_subscription_delete_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='payments.subscription', verbose_name='Тариф'),
        ),
    ]
