# Generated by Django 5.0.6 on 2024-10-28 15:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0005_goals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('success_assessment', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка по 10 бальной шкале')),
                ('success_reason', models.CharField(max_length=512, verbose_name='Причина успеха')),
                ('to_improve', models.CharField(max_length=512, verbose_name='Что улучшить')),
                ('subs_received', models.IntegerField(verbose_name='Получено подписчиков')),
                ('leads_received', models.IntegerField(verbose_name='Получено лидов/заявок')),
                ('sales_growth', models.CharField(max_length=128, verbose_name='Прирост продаж')),
                ('audience_reach', models.PositiveIntegerField(verbose_name='Охват аудитории')),
                ('bill_change', models.CharField(max_length=128, verbose_name='Изменение ср. чека')),
                ('new_offers', models.BooleanField(verbose_name='Новые предложения')),
                ('new_offers_comment', models.CharField(blank=True, max_length=512, verbose_name='Комментарий про предложения')),
                ('perception_change', models.BooleanField(verbose_name='Изменение восприятия бренда')),
                ('brand_compliance', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Соответствие брендов')),
                ('platform_help', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Помощь платформы')),
                ('difficulties', models.BooleanField(verbose_name='Трудности')),
                ('difficulties_comment', models.CharField(blank=True, max_length=512, verbose_name='Комментарий про трудности')),
                ('collab_with', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collab_participant', to='brand.brand', verbose_name='Коллаборация с')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collab_reporter', to='brand.brand', verbose_name='Кто поделился')),
            ],
        ),
    ]
