# Generated by Django 5.0.6 on 2024-06-16 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0006_alter_brand_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category',
                                               to='brand.brand')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.RemoveField(
            model_name='brand',
            name='formats',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='avg_bill',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='business_category',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='collab_with',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='fi',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='inst_profile_url',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='published',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='sub_expire',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='subs_count',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='territory',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='tg_brand_url',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='values',
        ),
        migrations.AddField(
            model_name='brand',
            name='business_group',
            field=models.CharField(blank=True, max_length=512, verbose_name='Сообщество предпринимателей'),
        ),
        migrations.AddField(
            model_name='brand',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Эл. почта'),
        ),
        migrations.AddField(
            model_name='brand',
            name='fullname',
            field=models.CharField(blank=True, max_length=512, verbose_name='Фамилия и имя'),
        ),
        migrations.AddField(
            model_name='brand',
            name='mission_statement',
            field=models.CharField(blank=True, max_length=512, verbose_name='Миссия бренда'),
        ),
        migrations.AddField(
            model_name='brand',
            name='phone',
            field=models.CharField(blank=True, max_length=12, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='brand',
            name='problem_solving',
            field=models.CharField(blank=True, max_length=512, verbose_name='Какую проблему решает'),
        ),
        migrations.AddField(
            model_name='brand',
            name='product_description',
            field=models.CharField(blank=True, max_length=512, verbose_name='Описание продукта'),
        ),
        migrations.AddField(
            model_name='brand',
            name='unique_product_is',
            field=models.CharField(blank=True, max_length=512, verbose_name='Уникальность продукта'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name_pos',
            field=models.CharField(max_length=512, verbose_name='Название бренда и должность'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_site_url',
            field=models.CharField(max_length=512, verbose_name='Сайт бренда'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='inst_brand_url',
            field=models.CharField(max_length=512, verbose_name='Бренд в Instagram'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='target_audience',
            field=models.CharField(max_length=512, verbose_name='Целевая аудитория'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='tg_nickname',
            field=models.CharField(max_length=64, verbose_name='Ник в телеграме'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='topics',
            field=models.CharField(max_length=512, verbose_name='Темы'),
        ),
        migrations.CreateModel(
            name='AvgBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avg_bill', to='brand.brand')),
            ],
            options={
                'verbose_name': 'Средний чек',
                'verbose_name_plural': 'Средний чек',
            },
        ),
        migrations.CreateModel(
            name='CollaborationInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_interest', to='brand.brand')),
            ],
            options={
                'verbose_name': 'Интересующая коллаборация',
                'verbose_name_plural': 'Интересующие коллаборации',
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='brand.brand')),
            ],
            options={
                'verbose_name': 'Формат взаимодействия',
                'verbose_name_plural': 'Форматы взаимодействия',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='brand.brand')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
            },
        ),
        migrations.CreateModel(
            name='PresenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence_type', to='brand.brand')),
            ],
            options={
                'verbose_name': 'Способ размещения бренда',
                'verbose_name_plural': 'Способы размещения бренда',
            },
        ),
        migrations.CreateModel(
            name='ReadinessPublicSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_speaker', to='brand.brand')),
            ],
            options={
                'verbose_name': 'Готовность быть спикером',
                'verbose_name_plural': 'Готовность быть спикером',
            },
        ),
        migrations.CreateModel(
            name='SubsCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subs_count', to='brand.brand')),
            ],
            options={
                'verbose_name': 'Кол-во подписчиков',
                'verbose_name_plural': 'Кол-во подписчиков',
            },
        ),
        migrations.DeleteModel(
            name='Formats',
        ),
        migrations.DeleteModel(
            name='Goals',
        ),
    ]
