# Generated by Django 5.0.6 on 2024-11-20 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0007_brand_city'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geo',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geos', to='cities_light.city', verbose_name='Город'),
        ),
    ]
