# Generated by Django 5.0.6 on 2024-06-16 19:49
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0008_alter_brand_business_group_alter_brand_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='brand',
            name='sub_expire',
            field=models.DateField(null=True, verbose_name='Окончание подписки'),
        ),
        migrations.AddField(
            model_name='brand',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brands',
                                    to='payments.subscription', verbose_name='Тариф'),
        ),
    ]
