# Generated by Django 5.0.6 on 2024-11-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0008_alter_geo_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='description',
        ),
    ]
