# Generated by Django 5.0.6 on 2024-11-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0009_remove_brand_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='sub_expire',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='subscription',
        ),
    ]
