# Generated by Django 5.0.6 on 2024-06-17 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0010_rename_name_avgbill_text_rename_name_category_text_and_more'),
        ('questionnaire', '0003_alter_answerchoice_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avgbill',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.question'),
        ),
        migrations.AddField(
            model_name='category',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.question'),
        ),
        migrations.AddField(
            model_name='collaborationinterest',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.question'),
        ),
        migrations.AddField(
            model_name='format',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.question'),
        ),
        migrations.AddField(
            model_name='goal',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.question'),
        ),
        migrations.AddField(
            model_name='presencetype',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.question'),
        ),
        migrations.AddField(
            model_name='readinesspublicspeaker',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.question'),
        ),
        migrations.AddField(
            model_name='subscount',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.question'),
        ),
    ]
