# Generated by Django 5.0.6 on 2025-01-24 15:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0010_remove_brand_sub_expire_remove_brand_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='collaborations', to='brand.match', verbose_name='Метч'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='like_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время лайка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='match_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Время метча'),
        ),
    ]
