# Generated by Django 5.0.6 on 2024-06-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0011_avgbill_question_category_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='email',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='phone',
        ),
    ]
