# Generated by Django 5.0.6 on 2024-06-18 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0011_avgbill_question_category_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_match', models.BooleanField(default=False, verbose_name='Метч')),
                ('brand1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand1_match', to='brand.brand', verbose_name='Бренд 1')),
                ('brand2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand2_match', to='brand.brand', verbose_name='Бренд 2')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='likes',
            field=models.ManyToManyField(through='brand.Match', to='brand.brand', verbose_name='Лайкнул'),
        ),
    ]
