# Generated by Django 5.1.6 on 2025-03-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0012_alter_brand_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='age',
            options={'verbose_name': 'Возраст', 'verbose_name_plural': 'Возраст'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
        migrations.AlterModelOptions(
            name='businessgroup',
            options={'verbose_name': 'Сообщество предпринимателей', 'verbose_name_plural': 'Сообщества предпринимателей'},
        ),
        migrations.AlterModelOptions(
            name='collaboration',
            options={'verbose_name': 'Collaboration', 'verbose_name_plural': 'Collaborations'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
    ]
