# Generated by Django 5.0.6 on 2024-08-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0012_match'),
        ('brand', '0012_remove_brand_email_remove_brand_phone'),
    ]

    operations = [
    ]
