# Generated by Django 5.1.6 on 2025-03-31 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0013_alter_age_options_alter_blog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='published',
        ),
    ]
