# Generated by Django 5.0.6 on 2024-09-02 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0013_merge_20240818_2042'),
        ('chat', '0002_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.room'),
        ),
    ]
