# Generated by Django 5.0.6 on 2024-09-08 12:21

import core.apps.brand.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0014_match_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(null=True, upload_to=core.apps.brand.models.user_directory_path, verbose_name='Лого'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='photo',
            field=models.ImageField(null=True, upload_to=core.apps.brand.models.user_directory_path, verbose_name='Фото представителя'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='product_photo',
            field=models.ImageField(null=True, upload_to=core.apps.brand.models.user_directory_path, verbose_name='Фото продукта'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
