# Generated by Django 5.0.6 on 2024-09-08 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0015_alter_brand_logo_alter_brand_photo_and_more'),
        ('chat', '0003_alter_room_participants_alter_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiator', to='brand.brand', verbose_name='Кто лайкнул'),
        ),
        migrations.AlterField(
            model_name='match',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.room'),
        ),
        migrations.AlterField(
            model_name='match',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target', to='brand.brand', verbose_name='Кого лайкнули'),
        ),
    ]
