# Generated by Django 5.0.6 on 2024-09-08 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0016_alter_match_initiator_alter_match_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avgbill',
            name='brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='avg_bill', to='brand.brand'),
        ),
        migrations.AlterField(
            model_name='category',
            name='brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='brand.brand'),
        ),
        migrations.AlterField(
            model_name='collaborationinterest',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaboration_interest', to='brand.brand'),
        ),
        migrations.AlterField(
            model_name='format',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formats', to='brand.brand'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='brand.brand'),
        ),
        migrations.AlterField(
            model_name='presencetype',
            name='brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='presence_type', to='brand.brand'),
        ),
        migrations.AlterField(
            model_name='readinesspublicspeaker',
            name='brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='public_speaker', to='brand.brand'),
        ),
        migrations.AlterField(
            model_name='subscount',
            name='brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subs_count', to='brand.brand'),
        ),
    ]
