# Generated by Django 5.0.6 on 2024-09-11 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0017_alter_avgbill_brand_alter_category_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collab_with', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collab_participant', to='brand.brand', verbose_name='Коллаборация с')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collab_reporter', to='brand.brand', verbose_name='Кто поделился')),
            ],
        ),
    ]
