# Generated by Django 5.0.6 on 2024-06-15 17:44
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField()),
                ('text', models.CharField(max_length=2048)),
                ('answer_type', models.CharField(choices=[('TEXT', 'Текстовый ввод'), ('ONE', 'Единственный выбор'),
                                                          ('MANY', 'Множественный выбор')], max_length=8)),
                ('index', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('question',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_variable',
                                   to='questionnaire.question')),
                ('index', models.PositiveIntegerField()),
            ],
        ),
    ]
