# Generated by Django 5.0.6 on 2024-06-15 17:56

from django.db import migrations, models


def add_questions(apps, schema_editor):
    Question = apps.get_model("questionnaire", "Question")
    AnswerChoice = apps.get_model("questionnaire", "AnswerChoice")
    question_1 = Question(
        published=True,
        text='Ваш ник в телеграм',
        answer_type='TEXT',
        index=1
    )
    question_1.save()
    question_2 = Question(
        published=True,
        text='Укажите ваш номер телефона',
        answer_type='TEXT',
        index=2
    )
    question_2.save()
    question_3 = Question(
        published=True,
        text='Название Вашего бренда и должность',
        answer_type='TEXT',
        index=3
    )
    question_3.save()
    question_4 = Question(
        published=True,
        text='К какой категории относится ваш бизнес?',
        answer_type='ONE',
        index=4
    )
    question_4.save()
    question_5 = Question(
        published=True,
        text='Ссылка на страницу бренда в запрещенной соц. сети',
        answer_type='TEXT',
        index=5
    )
    question_5.save()
    question_6 = Question(
        published=True,
        text='Ссылка на сайт бренда или на маркетплейс (WB, OZON, Lamoda, Яндекс Маркет)',
        answer_type='TEXT',
        index=6
    )
    question_6.save()
    question_7 = Question(
        published=True,
        text='У вас online или offline бренд?',
        answer_type='ONE',
        index=7
    )
    question_7.save()
    question_8 = Question(
        published=True,
        text='На какие темы с тобой можно пообщаться? Или по каким темам ты можешь дать рекомендации?',
        answer_type='TEXT',
        index=8
    )
    question_8.save()
    question_9 = Question(
        published=True,
        text='Готовы ли вы быть спикером прямого эфира или участвовать в публичном выступлении для резидентов?',
        answer_type='ONE',
        index=9
    )
    question_9.save()
    question_10 = Question(
        published=True,
        text='Сколько подписчиков у Вашего бренда в запрещенной сети?',
        answer_type='ONE',
        index=10
    )
    question_10.save()
    question_11 = Question(
        published=True,
        text='Средний чек вашего бренда (в рублях)?',
        answer_type='ONE',
        index=11
    )
    question_11.save()
    question_12 = Question(
        published=True,
        text='Опишите ключевую миссию Вашего бренда?',
        answer_type='TEXT',
        index=12
    )
    question_12.save()
    question_13 = Question(
        published=True,
        text='Расскажите нам о ядре вашей целевой аудитории. Пожалуйста, укажите: пол, возраст, уровень дохода, ГЕО, интересы',
        answer_type='TEXT',
        index=13
    )
    question_13.save()
    question_14 = Question(
        published=True,
        text='Расскажите, пожалуйста, в чем уникальность вашего продукта?',
        answer_type='TEXT',
        index=14
    )
    question_14.save()
    question_15 = Question(
        published=True,
        text='Опишите, пожалуйста, как можно короче ваш товар или услугу',
        answer_type='TEXT',
        index=15
    )
    question_15.save()
    question_16 = Question(
        published=True,
        text='Расскажите, пожалуйста, какую проблему вы решаете для клиента?',
        answer_type='TEXT',
        index=16
    )
    question_16.save()
    question_17 = Question(
        published=True,
        text='Интересующие форматы для взаимодействия',
        answer_type='MANY',
        index=17
    )
    question_17.save()
    question_18 = Question(
        published=True,
        text='Цель коллаборации',
        answer_type='MANY',
        index=18
    )
    question_18.save()
    question_19 = Question(
        published=True,
        text='С бизнесом из какой категории вам было бы интересно сделать коллаборацию?',
        answer_type='MANY',
        index=19
    )
    question_19.save()
    question_20 = Question(
        published=True,
        text='Состоите ли вы в каком-то комьюнити/сообществе предпринимателей? Напишите, пожалуйста, название или добавьте ссылку на сообщество',
        answer_type='TEXT',
        index=20
    )
    question_20.save()
    question_21 = Question(
        published=True,
        text='Загрузите, пожалуйста, логотип вашего бренда:',
        answer_type='IMAGE',
        index=21
    )
    question_21.save()
    question_22 = Question(
        published=True,
        text='Загрузите, пожалуйста, ваше фото:',
        answer_type='IMAGE',
        index=22
    )
    question_22.save()
    question_23 = Question(
        published=True,
        text='Загрузите, пожалуйста, фото, иллюстрирующее ваш продукт (товар или услугу):',
        answer_type='IMAGE',
        index=23
    )
    question_23.save()
    question_24 = Question(
        published=True,
        text='Укажите Ваше имя и фамилию',
        answer_type='TEXT',
        index=24
    )
    question_24.save()
    question_25 = Question(
        published=True,
        text='Адрес вашей электронной почты',
        answer_type='TEXT',
        index=25
    )
    question_25.save()
    choices_q4 = [
        AnswerChoice(
            text='Красота и здоровье',
            question=question_4,
            index=1,
        ),
        AnswerChoice(
            text='Товары для детей',
            question=question_4,
            index=2,
        ),
        AnswerChoice(
            text='Одежда и обувь',
            question=question_4,
            index=3,
        ),
        AnswerChoice(
            text='HoReCa',
            question=question_4,
            index=4,
        ),
        AnswerChoice(
            text='Украшения',
            question=question_4,
            index=5,
        ),
        AnswerChoice(
            text='Услуги',
            question=question_4,
            index=6,
        ),
        AnswerChoice(
            text='Товары для дома',
            question=question_4,
            index=7,
        ),
        AnswerChoice(
            text='Фрилансеры / агентства',
            question=question_4,
            index=8,
        ),
        AnswerChoice(
            text='Инфлюенсеры / блогеры',
            question=question_4,
            index=9,
        ),
        AnswerChoice(
            text='Другое',
            question=question_4,
            index=10,
        ),
    ]

    choices_q7 = [
        AnswerChoice(
            text='Online',
            question=question_7,
            index=1,
        ),
        AnswerChoice(
            text='Offline',
            question=question_7,
            index=2,
        ),
        AnswerChoice(
            text='Оба варианта',
            question=question_7,
            index=3,
        ),
    ]
    choices_q9 = [
        AnswerChoice(
            text='Да',
            question=question_9,
            index=1,
        ),
        AnswerChoice(
            text='Нет',
            question=question_9,
            index=2,
        ),
    ]
    choices_q10 = [
        AnswerChoice(
            text='0 - 1.000',
            question=question_10,
            index=1,
        ),
        AnswerChoice(
            text='1.000 - 10.000',
            question=question_10,
            index=2,
        ),
        AnswerChoice(
            text='10.000 - 100.000',
            question=question_10,
            index=3,
        ),
        AnswerChoice(
            text='100.000 - 500.000',
            question=question_10,
            index=4,
        ),
        AnswerChoice(
            text='500.000+',
            question=question_10,
            index=5,
        ),
    ]
    choices_q11 = [
        AnswerChoice(
            text='0 - 1.000',
            question=question_11,
            index=1,
        ),
        AnswerChoice(
            text='1.000 - 10.000',
            question=question_11,
            index=2,
        ),
        AnswerChoice(
            text='10.000 - 100.000',
            question=question_11,
            index=3,
        ),
        AnswerChoice(
            text='100.000 - 500.000',
            question=question_11,
            index=4,
        ),
        AnswerChoice(
            text='500.000+',
            question=question_11,
            index=5,
        ),
    ]
    choices_q17 = [
        AnswerChoice(
            text='Не определилась с форматом, но открыта к обсуждению',
            question=question_17,
            index=1,
        ),
        AnswerChoice(
            text='Совместный reels',
            question=question_17,
            index=2,
        ),
        AnswerChoice(
            text='Выпустить совместный продукт',
            question=question_17,
            index=3,
        ),
        AnswerChoice(
            text='Совместный прямой эфир',
            question=question_17,
            index=4,
        ),
        AnswerChoice(
            text='Совместный пост',
            question=question_17,
            index=5,
        ),
        AnswerChoice(
            text='Провести совместное мероприятие',
            question=question_17,
            index=6,
        ),
    ]
    choices_q18 = [
        AnswerChoice(
            text='Рост продаж',
            question=question_18,
            index=1,
        ),
        AnswerChoice(
            text='Повышение узнаваемости и лояльности',
            question=question_18,
            index=2,
        ),
        AnswerChoice(
            text='Новая аудитория и охваты в соцсетях',
            question=question_18,
            index=3,
        ),
        AnswerChoice(
            text='Совместное творчество и усиление навыков',
            question=question_18,
            index=4,
        ),
        AnswerChoice(
            text='Другое',
            question=question_18,
            index=5,
        ),
        AnswerChoice(
            text='Свой вариант',
            question=question_18,
            index=6,
        ),
    ]
    choices_q19 = [
        AnswerChoice(
            text='Я открыта к экспериментам и категория партнера мне не важна',
            question=question_19,
            index=1,
        ),
        AnswerChoice(
            text='Образование и эксперты',
            question=question_19,
            index=2,
        ),
        AnswerChoice(
            text='HoReCa',
            question=question_19,
            index=3,
        ),
        AnswerChoice(
            text='Украшения',
            question=question_19,
            index=4,
        ),
        AnswerChoice(
            text='Услуги',
            question=question_19,
            index=5,
        ),
        AnswerChoice(
            text='Товары для дома',
            question=question_19,
            index=6,
        ),
        AnswerChoice(
            text='Красота и здоровье',
            question=question_19,
            index=7,
        ),
        AnswerChoice(
            text='Товары для детей',
            question=question_19,
            index=8,
        ),
        AnswerChoice(
            text='Одежда и обувь',
            question=question_19,
            index=9,
        ),
    ]
    for q in [
        *choices_q4,
        *choices_q7,
        *choices_q9,
        *choices_q10,
        *choices_q11,
        *choices_q17,
        *choices_q18,
        *choices_q19,
    ]:
        q.save()


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_questions)
    ]
