# Generated by Django 5.0.6 on 2024-06-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_question_answerchoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerchoice',
            options={'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос анкеты', 'verbose_name_plural': 'Вопросы анкеты'},
        ),
        migrations.AlterField(
            model_name='answerchoice',
            name='index',
            field=models.PositiveIntegerField(verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='answerchoice',
            name='text',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('TEXT', 'Текстовый ввод'), ('ONE', 'Единственный выбор'), ('MANY', 'Множественный выбор'), ('IMAGE', 'Загрузка изображения')], max_length=16),
        ),
        migrations.AlterField(
            model_name='question',
            name='index',
            field=models.PositiveIntegerField(verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=256),
        ),
    ]
