# Generated by Django 5.0.6 on 2024-06-15 17:56

from django.db import migrations, models


def add_questions(apps, schema_editor):
    Question = apps.get_model("questionnaire", "Question")

    del_question = Question.objects.filter(index__in=[2, 25])
    for q in del_question:
        q.delete()

    questions = Question.objects.filter(index__gt=1)

    for q in questions:
        q.index -= 1
        q.save()


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_alter_answerchoice_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.RunPython(add_questions)
    ]
