# Generated by Django 5.1.6 on 2025-03-31 16:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Промокод')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка, %')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('cost', models.PositiveIntegerField(verbose_name='Цена')),
                ('duration', models.DurationField(verbose_name='Продолжительность')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='GiftPromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gifts_as_giver', to='brand.brand', verbose_name='Даритель')),
                ('promocode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_promocodes', to='payments.promocode', verbose_name='Промокод')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Gift PromoCode',
                'verbose_name_plural': 'Gift PromoCodes',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала подписки')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания подписки')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
                ('upgraded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата-время апгрейда')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='brand.brand', verbose_name='Бренд')),
                ('gift_promocode', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='payments.giftpromocode', verbose_name='Подарочный промокод')),
                ('promocode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='payments.promocode', verbose_name='Промокод')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='payments.tariff', verbose_name='Тариф')),
                ('upgraded_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_upgraded_to', to='payments.tariff', verbose_name='Апгрейд c')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
