# Generated by Django 5.0.6 on 2024-11-24 14:56

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0010_remove_brand_sub_expire_remove_brand_subscription'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала подписки')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания подписки')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='brand.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('cost', models.PositiveIntegerField(verbose_name='Цена')),
                ('duration', models.DurationField(verbose_name='Продолжительность')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
        migrations.AddField(
            model_name='promocode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 24, 14, 56, 50, 343247, tzinfo=datetime.timezone.utc), verbose_name='Истекает'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка, %'),
        ),
        migrations.AddField(
            model_name='brandsubscription',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='payments.promocode', verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='brandsubscription',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='payments.tariff', verbose_name='Тариф'),
        ),
    ]
