# Generated by Django 5.1.6 on 2025-03-31 16:47
from datetime import timedelta

from django.db import migrations
from django.db.models import Q


def add_tariffs(apps, schema_editor):
    Tariff = apps.get_model('payments', 'Tariff')

    Tariff.objects.bulk_create([
        Tariff(
            name='Trial',
            cost=0,
            duration=timedelta(days=14)
        ),
        Tariff(
            name='Lite Match',
            cost=6000,
            duration=timedelta(days=3 * 30)
        ),
        Tariff(
            name='Business Match',
            cost=15000,
            duration=timedelta(days=3 * 30)
        )
    ])


def delete_tariffs(apps, schema_editor):
    Tariff = apps.get_model('payments', 'Tariff')

    Tariff.objects.filter(
        Q(name='Trial', cost=0)
        | Q(name='Lite Match', cost=6000)
        | Q(name='Business Match', cost=15000)
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_tariffs, delete_tariffs)
    ]
