# Generated by Django 5.0.6 on 2024-11-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0010_remove_brand_sub_expire_remove_brand_subscription'),
        ('payments', '0002_brandsubscription_tariff_delete_subscription_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrandSubscription',
            new_name='Subscription',
        ),
    ]
