# Generated by Django 5.0.6 on 2024-12-03 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_tariffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='upgraded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата-время апгрейда'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='upgraded_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_upgraded_to', to='payments.tariff', verbose_name='Апгрейд c'),
        ),
    ]
