# Generated by Django 5.0.6 on 2024-12-05 14:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0010_remove_brand_sub_expire_remove_brand_subscription'),
        ('payments', '0005_subscription_upgraded_at_subscription_upgraded_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftPromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gifts_as_giver', to='brand.brand', verbose_name='Даритель')),
                ('promocode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_promocodes', to='payments.promocode', verbose_name='Промокод')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.tariff', verbose_name='Тариф')),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='gift_promocode',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='payments.giftpromocode', verbose_name='Подарочный промокод'),
        ),
    ]
