# Generated by Django 5.1.6 on 2025-03-22 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_giftpromocode_subscription_gift_promocode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giftpromocode',
            options={'verbose_name': 'Gift PromoCode', 'verbose_name_plural': 'Gift PromoCodes'},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='gift_promocode',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='payments.giftpromocode', verbose_name='Подарочный промокод'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='upgraded_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_upgraded_to', to='payments.tariff', verbose_name='Апгрейд c'),
        ),
    ]
