# Generated by Django 5.0.6 on 2024-09-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('M', 'Match'), ('G', 'Guaranteed'), ('I', 'Instant')], default='M', max_length=1, verbose_name='Тип'),
        ),
    ]
