# Generated by Django 5.0.6 on 2025-01-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='has_business',
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('M', 'Match'), ('I', 'Instant'), ('S', 'Support')], default='M', max_length=1, verbose_name='Тип'),
        ),
    ]
