# Generated by Django 5.1.6 on 2025-03-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_roomfavorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='roomfavorites',
            options={'verbose_name': 'Room Favorites', 'verbose_name_plural': 'Room Favorites'},
        ),
    ]
